### ISSUE TITLE
Cannot find module 'jsonfile'

### ISSUE THREAD

**Issue by PetersonLian** [allmobilize/amazeui#453]
Error: Cannot find module 'jsonfile'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ablian/gitRepos/amazeui/node_modules/fs-extra/lib/index.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ablian/gitRepos/amazeui/gulpfile.js:7:10)
jsonfile?Where to locate?

**Comment by PetersonLian** [comment]
也是醉了，刚打不了中文 。
jsonfile模块在何处？哪里定位呢？
