### ISSUE TITLE
Bug: 按照 github上 Amaze UI 入门套件 一步一步操作 走到 gulp serve 的时候一直卡在这里过不去报错

### ISSUE THREAD

**Issue by gggso** [allmobilize/amazeui#521]
**问题描述**
按照 github上 Amaze UI 入门套件 一步一步操作 走到 gulp serve 的时候一直卡在这里过不去报错
https://github.com/amazeui/starter-kit
错误
➜  app git:(master) ✗ gulp serve
[17:09:25] Working directory changed to /wwwroot/starter-kit
[17:09:26] Using gulpfile /wwwroot/starter-kit/gulpfile.js
[17:09:26] Starting 'default'...
[17:09:26] Starting 'clean'...
[17:09:26] Finished 'clean' after 4.87 ms
[17:09:26] Starting 'styles'...
[17:09:27] Starting 'jshint'...
[17:09:27] Starting 'html'...
[17:09:27] Starting 'images'...
[17:09:29] Starting 'copy'...
[17:09:29] Starting 'browserify'...
[17:09:29] Finished 'browserify' after 2.2 ms
/wwwroot/starter-kit/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/wwwroot/starter-kit/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/wwwroot/starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/wwwroot/starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/wwwroot/starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/wwwroot/starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/wwwroot/starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/wwwroot/starter-kit/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at fsOperationFailed (/wwwroot/starter-kit/node_modules/gulp-changed/index.js:17:10)

**产生环境**

- 设备：Mac os
- 操作系统及版本：10.10
- 浏览器及版本：无
- 演示地址：无

**Comment by huangzhipeng** [comment]
已经修正 starter-kit gulp-less 版本，如果你已经克隆和安装，先卸载 gulp-less 重新安装 3.0.2 版本或者重新克隆下。

**Comment by suikaxin** [comment]
谢谢 huangzhipeng，同样的问题，卸载less后重新安装即可。
